apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Andres19a-Andres19a-poi-map-app-dev
  annotations:
    argocd/app-name: Andres19a-Andres19a-poi-map-app-dev
    backstage.io/kubernetes-id: Andres19a-Andres19a-poi-map-app-dev
    backstage.io/kubernetes-namespace: Andres19a
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=Andres19a-Andres19a-poi-map-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Summit23Janus1/Andres19a-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.summit23rock.n26o.p1.openshiftapps.com/dev-pipelines/ns/Andres19a/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.summit23rock.n26o.p1.openshiftapps.com/k8s/ns/Andres19a/deployments/Andres19a-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.summit23rock.n26o.p1.openshiftapps.com/#https://github.com/Summit23Janus1/Andres19a-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://Andres19a-poi-map-app-Andres19a.apps.summit23rock.n26o.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/andres19a"
  system: workshop-system-Andres19a
  consumesApis:
    - gateway-api-Andres19a
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-Andres19a
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/andres19a"
